#STORED PROCEDURES

#1. test_AreaNumShoppers:
	CREATE TEMPORARY TABLE TXN_UL_NUL1 select a.* from (select a.Country_Code, DATE(a.BILL_DATE) AS DATE_i, MONTH(BILL_DATE) AS MONTH_i, MAX(BILL_DATE) as BILL_DATE_max,  a.OUTLET_UNIQUE_CODE, a.BILL_NO, (SUM(case when b.COMPANY_CODE Like 'Unilever%' then 1 else 0 end)) AS UL_FLAG, a.TOTAL_LINE_AMT AS TOTAL_LINE_AMT 
	from NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging a, NEW_EMPORIO_GENESIS_IDN.Product_master_emporio b
	where a.BARCODE=b.BARCODE
	group by Country_Code, DATE_i,MONTH_i,a.OUTLET_UNIQUE_CODE, BILL_NO, TOTAL_LINE_AMT) a;

	#select DATE(BILL_DATE) AS DATE_i, MONTH(BILL_DATE) AS MONTH_i, HOUR(BILL_DATE) AS HOUR_FROM, HOUR(BILL_DATE)+1 AS HOUR_TO, OUTLET_UNIQUE_CODE, COUNT(DISTINCT BILL_NO) AS TOTAL_SHOPPERS, (SUM(case when UL_FLAG !='0' then 1 else 0 end)) AS UL_SHOPPERS, SUM(TOTAL_BILL_AMT)
	#FROM TXN_UL_NUL1
	#GROUP BY DATE_i,MONTH_i,HOUR_FROM,HOUR_TO,OUTLET_UNIQUE_CODE;

	select Country_Code, DATE_i, MONTH_i, HOUR(BILL_DATE_max) as HOUR_FROM, HOUR(BILL_DATE_max)+1 AS HOUR_TO, OUTLET_UNIQUE_CODE, COUNT(DISTINCT BILL_NO) AS TOTAL_SHOPPERS, (SUM(case when UL_FLAG !='0' then 1 else 0 end)) AS UL_SHOPPERS, SUM(TOTAL_LINE_AMT)
	FROM TXN_UL_NUL1
	GROUP BY Country_Code, DATE_i,MONTH_i,HOUR_FROM,HOUR_TO,OUTLET_UNIQUE_CODE; 
 #2. test_AreaSKUShare:
	 CREATE TEMPORARY TABLE SKUSHARE select NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging.COUNTRY_CODE, NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging.OUTLET_UNIQUE_CODE, DATE(NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging.BILL_DATE) AS SALE_DATE, NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging.BARCODE, SUM(LINE_ITEM_DISC_VAL) AS DISC_VALUE, MAX(CURR_SALES_PRICE) AS MAX_CURR_SALES_PRICE, MAX(MRP) AS MAX_MRP, SUM(QTY) AS TOTAL_QTY, SUM(TOTAL_LINE_AMT) AS TOTAL_LINE_AMT from NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging 

	INNER JOIN NEW_EMPORIO_GENESIS_IDN.Product_master_emporio ON NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging.BARCODE = NEW_EMPORIO_GENESIS_IDN.Product_master_emporio.BARCODE 
	where Product_master_emporio.BARCODE IS NOT NULL  

	GROUP BY NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging.COUNTRY_CODE,NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging.OUTLET_UNIQUE_CODE, SALE_DATE,NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging.BARCODE, NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging.OUTLET_UNIQUE_CODE;
	select * from SKUSHARE;
#3. test_AreaValShare
	CREATE TEMPORARY TABLE VALSHARE_NUL select a.COUNTRY_CODE, a.OUTLET_UNIQUE_CODE, a.COUNTER_NUM, a.BILL_NO, a.BILL_DATE, a.TOTAL_LINE, a.CUST_NAME, a.CUST_PH_NUM, a.BILL_LEVEL_TAX_VAL, a.BILL_LEVEL_DISC_VAL, a.ONLINE_FLAG, a.UPDATED_TIME, a.CUST_TYPE, a.LINE_ITEM_DISC_VAL,  ENCRYPT(Product_master_emporio.PROD_BRAND,'fractal123'), NEW_EMPORIO_GENESIS_IDN.Product_master_emporio.PROD_CATEGORY, NEW_EMPORIO_GENESIS_IDN.Product_master_emporio.PROD_SUB_CATEGORY, SUM(QTY) AS QTY, SUM(TOTAL_LINE_AMT) AS TOTAL_SALES_AMT from NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging a 

	INNER JOIN NEW_EMPORIO_GENESIS_IDN.Product_master_emporio ON a.BARCODE = NEW_EMPORIO_GENESIS_IDN.Product_master_emporio.BARCODE 
	where Product_master_emporio.BARCODE IS NOT NULL and Product_master_emporio.COMPANY_CODE NOT like 'Unilever%' 

	GROUP BY COUNTRY_CODE, OUTLET_UNIQUE_CODE, COUNTER_NUM, BILL_NO, BILL_DATE, TOTAL_LINE, CUST_NAME, CUST_PH_NUM, BILL_LEVEL_TAX_VAL, BILL_LEVEL_DISC_VAL, ONLINE_FLAG, UPDATED_TIME, CUST_TYPE, LINE_ITEM_DISC_VAL, NEW_EMPORIO_GENESIS_IDN.Product_master_emporio.PROD_BRAND, NEW_EMPORIO_GENESIS_IDN.Product_master_emporio.PROD_CATEGORY, NEW_EMPORIO_GENESIS_IDN.Product_master_emporio.PROD_SUB_CATEGORY;

	select * from VALSHARE_NUL;    
#4. test_OutletSKURepo
	CREATE TEMPORARY TABLE OUTLET_SKU_REPO select a.* from (select a.Country_Code, DATE(a.BILL_DATE) AS SALE_DATE, MONTH(a.BILL_DATE) AS SALE_MONTH,a.OUTLET_UNIQUE_CODE, (select distinct (a.BARCODE)) AS BARCODE
	from NEW_EMPORIO_GENESIS_IDN.Transactions_emporio_staging a 

	INNER JOIN NEW_EMPORIO_GENESIS_IDN.Product_master_emporio ON a.BARCODE = NEW_EMPORIO_GENESIS_IDN.Product_master_emporio.BARCODE 
	where Product_master_emporio.BARCODE IS NOT NULL  

	GROUP BY a.Country_Code, a.BILL_DATE,a.OUTLET_UNIQUE_CODE, a.BARCODE) a;
	select * from OUTLET_SKU_REPO;    